export const surpriseMePrompts = [
"A watercolor painting of a unicorn riding a rainbow through a forest",
"A photograph of a lion wearing a top hat and monocle, sitting in a library",
"A 3D render of a futuristic city skyline at sunset, with flying cars and floating buildings",
"A pencil sketch of a mermaid lounging on a rock in the ocean, surrounded by fish",
"An oil painting of a dragon sleeping on a treasure hoard, with knights sneaking around in the background",
"A photograph of a bird's nest made entirely out of human-made objects, like bottle caps and shoelaces",
"A digital art piece of a steampunk elephant with mechanical gears and pipes protruding from its body",
"A watercolor portrait of a woman with colorful flowers growing out of her hair",
"A 3D render of a giant robot spider climbing up a skyscraper in a cyberpunk city",
"An oil painting of a polar bear playing the piano in a snow-covered forest",
"A photograph of a city street at night, with all the lights turned off except for one glowing street lamp",
"A digital art piece of a group of aliens playing soccer with a planet as the ball",
"A pencil drawing of a tree with branches made of human arms and hands reaching out",
"A 3D render of a futuristic underwater city with bioluminescent plants and animals",
"An oil painting of a phoenix rising from the ashes of a burned-down forest",
"A photograph of a group of people dressed in traditional clothing from different countries, all standing together in front of a city skyline",
"A digital art piece of a cyborg mermaid swimming in a polluted ocean",
"A watercolor painting of a giant snail carrying a small house on its back, with a garden growing on the roof",
"A 3D render of a neon-lit arcade from the 1980s, with pixelated video game characters on the walls",
"An oil painting of a giant octopus playing the drums in a jazz band",
"A photograph of a city street covered in fog, with only the silhouette of a person visible in the distance",
"A digital art piece of a robot gardener tending to a garden on a rooftop in a city",
"A pencil drawing of a tree with branches made of musical instruments",
"A 3D render of a space station orbiting a gas giant planet, with colorful storms raging in the background",
"An oil painting of a group of fairies playing instruments in a moonlit forest.",
"A whimsical watercolor painting of a teapot with legs and a face",
"A photograph of a misty forest with a waterfall in the distance",
"A digital art piece of a neon city skyline at night",
"A portrait in oil paint of an elderly man with a kind smile",
"A pencil drawing of a horse and rider jumping over a fence",
"A photograph of a beach at sunset with seagulls flying overhead",
"A surrealist oil painting of a giant snail crawling up a clock tower",
"A digital art piece of a futuristic city with flying cars and towering skyscrapers",
"An oil painting of a vase of sunflowers on a windowsill",
"A photograph of a group of penguins huddled together on an ice floe",
"A charcoal sketch of a still life with a skull and candle",
"A digital art piece of a dragonfly with wings made of stained glass",
"An oil painting of a mountain landscape with a river flowing through it",
"A 3D render of a futuristic city with hovering drones and holographic billboards",
"A digital art piece of a mermaid sitting on a rock in the ocean, staring off into the distance",
"An oil painting of a still life with fruit and flowers arranged in a wicker basket",
"A photograph of a herd of wild horses running across an open plain",
"A surrealist digital art piece of a faceless mannequin with a bouquet of flowers for a head",
"A watercolor painting of a cozy cottage nestled in a forest clearing",
"A charcoal sketch of a street musician playing a guitar in the rain",
"A digital art piece of a woman with rainbow hair and butterfly wings standing in a field of flowers",
"An oil painting of a sunset over a tranquil lake, with mountains in the distance",
"A photograph of a lightning storm over a city skyline",
"A mixed media collage of a cityscape made with torn magazine pages and colored paper",
"A digital art piece of a neon jungle with bioluminescent plants and animals",
"A charcoal sketch of a lion resting in the shade of a tree in the savannah",
"An oil painting of a winter landscape with snow-covered trees and a frozen river",
"A photograph of a group of hot air balloons flying over a desert at sunrise",

];